version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - postgres
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7.4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: nazararik585@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres
    depends_on:
      - postgres

  mail_service:
    build:
      context: ./mailService
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL: ${RABBITMQ_URL}
      - EMAIL_FROM: ${EMAIL_FROM}
      - EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      - EMAIL_SMTP_SERVER: ${EMAIL_SMTP_SERVER}
      - EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  postgres:
    driver: bridge

volumes:
  pgadmin-data:
  postgres: